backend:
  name: git-gateway 
  identity_url: https://juji.io/.netlify/identity 
  gateway_url:  https://juji.io/.netlify/git 

local_backend: true # for local dev

publish_mode: editorial_workflow

site_url: https://juji.io
logo_url: https://juji.io/assets/img/ui/ui--logo.png
    
media_library:
  name: uploadcare
  config:
    publicKey: f1633d22bf0d766b5935
  settings:
    autoFilename: true
    defaultOperations: "/resize/800x600/"

media_folder: "assets/uploads" # Folder where user uploaded files should go
public_folder: "/assets/uploads"

show_preview_links: true

collections: # A list of collections the CMS should be able to edit
  - name: "blog" # Used in routes, ie.: /admin/collections/:slug/edit
    identifier_field: "title"
    label: "Article" # Used in the UI, ie.: "New Post"
    folder: "blog" # The path to the folder where the documents are stored
    slug: "{{slug}}" # Filename template, e.g., title.md
    preview_path: blog/{{slug}}
    extension: md
    format: frontmatter
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog/article.njk"}
      - {label: "Status", name: "status", widget: "select", default: "draft", options: ["draft", "published"], hint: "Draft does not show on site"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false, hint: "Featured article appears among the top 5 on the blog homepage"}
      - {label: "Title", name: "title", widget: "string", hint: "Good title uses number, 'how to', adjectives, famous thing, scarcity, promises, etc., and appeal to emotions."}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Category", name: "category", widget: "select", default: "Guides", options: ["Guides", "News", "Viewpoints", "Engineering"], hint: "Select a category"}
      - {label: "Tags", name: "tags", widget: "list", hint: "Enter comma-separated values, please reuse existing tags as much as possible"}
      - {label: "Featured Image", name: "image", widget: "image", hint: "Featured image shows as the article cover"}
      - {label: "Body", name: "body", widget: "markdown"}
